Add light sensor component for veml7700 light sensor
smartknob-ha/firmware pull request #37
Opened 2024-03-02 17:33 UTC by Ricovl

2024-03-02 17:40 UTC, SquaredPotato requested changes

2024-03-02 17:40 UTC, SquaredPotato commented on components/light_sensor/include/light_sensor.hpp
> +class light_sensor : public component {
indentation in this class is wacky, please use the .clang_format

2024-03-02 17:40 UTC, SquaredPotato commented on components/light_sensor/src/light_sensor.cpp
> +	return Ok(INITIALIZING);
extra indent?

2024-03-02 17:40 UTC, SquaredPotato commented on components/light_sensor/include/light_sensor.hpp
> +    Result<uint32_t, etl::string<128>> read_light_level();
We should add a type in the SDK for error strings, I'll add an issue

2024-03-02 17:53 UTC, SquaredPotato approved these changes

2024-03-03 10:46 UTC, abrondijk commented on components/light_sensor/src/light_sensor.cpp
> +        m_conf.shutdown = 1;
What does this do?

2024-03-03 10:51 UTC, abrondijk approved these changes

2024-03-03 11:01 UTC, merged